name: Generate documentation

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master
jobs:
  generate_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Build docs
        run: npm run build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: documentation-${{github.sha}}
          path: build/site
  push_to_gh_pages:
    # only when 'on push to master'
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') &&  github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: generate_doc
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: documentation-${{github.sha}}
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
          user_name: 'bonitasoft-documentation-bot'
          user_email: 'bonitasoft-documentation-bot@users.noreply.github.com'
